### PR TITLE
Upgrade docker build to buildx

### PR DESCRIPTION
**Pull request by egalpin**
## Summary

Update to use `docker buildx build` instead of `docker build`

### Checklist

- [ ] My comments/docstrings/type hints are clear
- [ ] I've written new tests or this change does not need them
- [ ] I've tested this manually
- [ ] The architecture diagrams have been updated, if need be
- [ ] I've included any special rollback strategies above
- [ ] Any relevant metrics/monitors/SLOs have been added or modified
- [ ] I've notified all relevant stakeholders of the change
- [ ] I've updated .github/CODEOWNERS, if relevant

### CODE REVIEW

**Review by TheKevJames — APPROVED** [review]

**Review by sschulzdialpad — CHANGES_REQUESTED** [review]
I think we have to pause this for the time being since cross platform builds are painfully slow.
A build step that took on `arm64` 70 seconds hasn't completed yet after 1 hour of execution on `amd64`.

**Comment by caseydialpad** [comment]
> I think we have to pause this for the time being since cross platform builds are painfully slow. A build step that took on `arm64` 70 seconds hasn't completed yet after 1 hour of execution on `amd64`.

This slowdown is likely due to  the amd64 being emulated. One way to accelerate this might be to update the Dockerfile as described at in [Faster Multi-Platform Builds](https://www.docker.com/blog/faster-multi-platform-builds-dockerfile-cross-compilation-guide/). If emulation is the issue, then the solution would be to run everything on the native architecture and compile to the target architecture.

If there is no compiling then the solution might be to build on the same architecture as the target to eliminate the need for emulation.

For python, since some dependencies may need to be compiled, setting the compiler environment variables for subsequent compilers to use may do the trick. Now whether or not those environment variables will be read correctly is another problem all together.

**Comment by sschulzdialpad** [comment]
@caseydialpad Good call - in our case since we are building a jar we should be able to build the jar entirely on a build stage using $BUILDPLATFORM` and then copy it over to a build stage running on the native architecture. 

One thing to note for this PR is that `buildx` needs to be setup before it can be used:
```
docker buildx create --name multiplatformbuilder
docker buildx use  multiplatformbuilder
```
and then we can use it to build like:
```
docker buildx build --platform linux/arm64 -t seb-test:latest .
```

**Comment by caseydialpad** [comment]
> @caseydialpad Good call - in our case since we are building a jar we should be able to build the jar entirely on a build stage using $BUILDPLATFORM` and then copy it over to a build stage running on the native architecture.
> 
> One thing to note for this PR is that `buildx` needs to be setup before it can be used:
> 
> ```
> docker buildx create --name multiplatformbuilder
> docker buildx use  multiplatformbuilder
> ```
> 
> and then we can use it to build like:
> 
> ```
> docker buildx build --platform linux/arm64 -t seb-test:latest .
> ```

If those steps need to be done before the main `steps` of CircleCI run, you could use the `pre-step` syntax to make it so. It would look as follows:

``` yaml
- docker/build:
          name: name-of-build-platform-and-job
          ...
          build_args: --platform linux/arm64
          pre-steps:
            - run: docker buildx create --name multiplatformbuilder
            - run: docker buildx use  multiplatformbuilder
```

And that should do the trick for you.

**Comment by sschulzdialpad** [comment]
> > @caseydialpad Good call - in our case since we are building a jar we should be able to build the jar entirely on a build stage using $BUILDPLATFORM` and then copy it over to a build stage running on the native architecture.
> > One thing to note for this PR is that `buildx` needs to be setup before it can be used:
> > ```
> > docker buildx create --name multiplatformbuilder
> > docker buildx use  multiplatformbuilder
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and then we can use it to build like:
> > ```
> > docker buildx build --platform linux/arm64 -t seb-test:latest .
> > ```
> 
> @sschulzdialpad,
> 
> I see what you're saying. If those steps need to be done before the main `steps` of CircleCI run, you could use the `pre-step` syntax to make it so. It would look as follows:
> 
> ```yaml
> - docker/build:
>           name: name-of-build-platform-and-job
>           ...
>           build_args: --platform linux/arm64
>           pre-steps:
>             - run: docker buildx create --name multiplatformbuilder
>             - run: docker buildx use  multiplatformbuilder
> ```
> 
> And that should do the trick for you.

Excellent sounds good with the pre-steps! 
Regarding this PR here - would it make sense to keep `docker/build` like it is and additionally introduce `docker/buildx` so that we can do a step wise migration to buildx for all internal docker builds?

**Review by kylepad — APPROVED** [review]

**Comment by sschulzdialpad** [comment]
The docker version we are using doesn't have `dockerx` enabled per default - investigating how I can change this..

**Comment by sschulzdialpad** [comment]
Can we try upgrading `setup_remote_docker` versions in this repository to `20.10.11` and see if this changes things?  (Can't do it myself since I don't have access this repo)

**Comment by sschulzdialpad** [comment]
@TheKevJames and me debugged this the other day. Turns out that `buildx` is not included in the official docker image https://github.com/docker/roadmap/issues/322. 
I'll pick this up again a bit later when I have worked off some other things off my plate :)  
To move forward here we probably have to install buildx on the docker image and then use that (https://docs.docker.com/buildx/working-with-buildx/#install).

**Review by caseydialpad — APPROVED** [review]

**Comment by TheKevJames** [comment]
Closing as stale

**Pull request closed without merging**
