### PR TITLE
feat(docs): create docs archive on every doc build

### PR DESCRIPTION
**Pull request by amartsinovich-dialpad**
## Summary

Archive all rendered docs on each compile & upload step. This will allow workbench to watch archive, download it on each change and serve as static files. This will allow to:
1. ditch docs cloud-run service
2. update docs immediately rather than daily

### Checklist

- [ ] comments/docstrings/type hints are clear
- [ ] new tests have been written
- [ ] manual testing has passed
- [ ] architecture diagrams have been updated
- [ ] I've included any special rollback strategies above
- [ ] metrics/monitors/alerts/SLOs have been added or modified

### CODE REVIEW

**Review by TheKevJames — COMMENTED** [review]
Mentioned in 1:1 but mirroring here for comments from others:

I'm not sure about the value of re-uploading a tarball here compared to making use of the files as-is; rather than needing to watch the single tarball file, we can set up an OCN on the bucket as is so Workbench gets a pubsub notification on any change. As an added benefit, keeping the files separate means Workbench would only need to download the changed files rather than everything, if it likes.

**Comment by amartsinovich-dialpad** [comment]
Yeah, that's totally reasonable and we go that route. The only unpleasant detail is that workbench will have to bear some additional complexity for initial file downloads. There's also an open question of how to make local runs convenient. I guess we can dynamically create and delete subscriptions? 🤔

**Comment by TheKevJames** [comment]
Well I think _either way_ Workbench needs to "download all docs on startup". Not sure it's any different for that process to be `gsutil cp gs://foo-docs-archive/docs.tar.gz && tar xzf docs.tar.gz /docs/on/disk` vs `gsutil -m cp -r gs://foo-docs/ /docs/on/disk`?

Hmm are you thinking to have local runs of workbench _also_ have auto-updating docs? Yeah, creating/deleting new subscriptions makes sense; theoretically, we'd want every instance of workbench to get the trigger anyway once we start having >1 instance, so we'd want each workbench to create a new subscription on startup anyway.

**Comment by amartsinovich-dialpad** [comment]
>Well I think either way Workbench needs to "download all docs on startup"
Yes, but API does not support bulk fetch, so that's be 1600+ requests :) Not a problem tho, just an overhead

>Hmm are you thinking to have local runs of workbench also have auto-updating docs?
It may totally be disabled by default, but it should work locally at least for the purpose of the development of this very feature :D

**Review by harsh-dialpad — COMMENTED** [review]
Might not be relevant depending on how other things are architected, but it is technically possible to just serve the pages directly off GCS without having to worry about updates/etc.

https://cloud.google.com/storage/docs/static-website
https://cloud.google.com/storage/docs/hosting-static-website
https://cloud.google.com/storage/docs/troubleshooting#https

**Comment by amartsinovich-dialpad** [comment]
@harsh-dialpad IIRC the main concern is that it doesn't support authentication https://issuetracker.google.com/issues/114133245 🤔

**Comment by harsh-dialpad** [comment]
Makes sense. Interesting that they don't have the feature though. Thanks for the link!

**Comment by TheKevJames** [comment]
Yup, our current docs cloudrun app basically exists for the exclusive purpose of working around that feature request haha.

> Yes, but API does not support bulk fetch, so that's be 1600+ requests :) Not a problem tho, just an overhead

Ugh, gross, what sort of file download API doesn't implement bulk fetch *grumble grumble*.

**Pull request closed without merging**
